---
- name: /etc/myhosts file create
  hosts: dev
  tasks:
  - name: /etc/myhosts file create task
    template:
      src: templates/hosts.j2
      dest: /etc/myhosts
      mode: '0644'
      group: root 
      owner: root
