---
# task file
- name: 패키지 설치 - {{ packages }}
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: present

- name: 서비스 기동 - {{ services }}
  ansible.builtin.systemd:
    name: "{{ services }}"
    enabled: true
    state: started

...
