---
- name: 웹 서버 설정
  hosts: webservers
  tasks:
    ###
    # play01
    # 1) 웹서버 패키지 설치 및 기동 - include_tasks
    # 2) 방화벽 패키지 설치 및 기동, 포트 등록 - import_tasks
    # 3) 웹서버 설정(/var/www/html/index.html) - import_tasks

    # play02
    # 4) 웹 요청 - import_tasks
    - name: 1) 웹서버 패키지 설치 및 기동
      ansible.builtin.include_tasks: tasks/web.yml
      vars:
        packages:
          - httpd
          - mod_ssl
        services: httpd
      when: ansible_os_family == "RedHat"
  
    - name: 2) 방화벽 패키지 설치 및 기동, 포트 등록
      ansible.builtin.import_tasks: tasks/fw.yml
      vars:
        packages:
          - firewalld
        services: 
          - firewalld
        rules:
          - http
          - https

    - name: 3) 웹서버 설정
      ansible.builtin.import_tasks: tasks/placeholder.yml
      vars:
        file: /var/www/html/index.html

- name: 웹 요청 테스트
  ansible.builtin.import_playbook: plays/test.yml
  vars:
    url: "http://ansible1.example.com"
...

