---
- name: 01) 파일 서버 설정
  hosts: fileservers
  tasks:
    - name: 1) 변수 포함
      ansible.builtin.include_vars: 
          dir: .
          files_matching: paths.yml
    
    - name: 2) 원격 디렉토리 생성
      ansible.builtin.file:
        path: "{{ paths.fileserver }}"
        state: directory
        owner: ansible
        group: ansible
        mode: "0755"
      register: web_output
    
    - name: 3) 디버깅 메세지
      ansible.builtin.debug:
        var: web_output.path
        