---
- name: job start
  hosts: all
  remote_user: ansible
  become: false
  gather_facts: false
  tasks:
    - name: job start
      cron:
        name: datejob
        job: "date >> /home/ansible/datefile"
        minute: '0,30'
        hour: '*'
        month: '*'
        day: '*'
        month: '*'
        weekday: '1-5'

