---
###
# 1) 방화벽 포트 제거 (firewalld - mysql, http, https)
# 2) 서비스 종료 (sysyemd - httpd, mariadb)
# 3) 서비스 설정에서 웹 서버 파일 삭제 (file)
# 4) 패키지 삭제
- name: 0) 복구 작업
  hosts: webservers
  tasks:
    - name: 1) 방화벽 포트 제거
      ansible.posix.firewalld:
        service: item
        state: disabled
        permanent: true
      loop:
        - mysql
        - http
        - https

    - name: 2) 서비스 종료 제거
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - mariadb
        - httpd
    
    - name: 3) 서비스 설정에서 웹 서버 파일 삭제
      ansible.builtin.file:
        path: /var/www/html/index.php
        state: absent
    
    - name: 4) db 패키지 제거
      ansible.builtin.dnf:
        name: item
        state: absent
      loop:
        - httpd
        - mod_ssl
        - php
        - mariadb
        - mariadb-server
        - python3-PyMySQL
...
