---
- name: 0) 모듈 테스트 - copy and lineinfile
  hosts: all
  tasks:
    - name: 1) 대상 호스트에 파일 배포
      ansible.builtin.copy:
        src: ~/files/user.txt
        dest: /home/devops/user.txt
        owner: devops
        group: devops
        mode: '0640'

    - name: 2) 파일에 라인 추가
      ansible.builtin.lineinfile:
        path: /home/devops/user.txt
        line: '추가된 라인'
        state: present
