---
- name: Restore intranet.yml
  hosts: all
  tasks:
    - name: 방화벽에서 서비스 제거
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: disabled
        immediate: true
    
    - name: 웹 서비스, 방화벽 중지
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - httpd
        - firewalld 
    
    - name: 파일 삭제
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 패키지 삭제
      ansible.builtin.dnf:
        name: httpd
        state: absent
...