---
- name: 0) DB 서비스 기동 - loop 테스트
  hosts: database_dev
  gather_facts: true
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
    db_svc: mariadb
  tasks:
    ###
    # 1) 패키지 설치
    # 2) 서비스 기동 - maria
    ###
    - name: 1) 패키지 설치
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ mariadb_packages }}"
      #when: ansible_distribution == "RedHat"
      when: ansible_distribution == "CentOS"
        
    - name: 2) 서비스 기동
      ansible.builtin.systemd:
        name: "{{ db_svc }}"
        state: started
        enabled: true
...
