---
- name: Restore
  hosts: all
  gather_facts: true
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMysql
    db_svc: mariadb
  tasks:
    - name: 1) 서비스 종료
      ansible.builtin.systemd:
        name: "{{ db_svc }}"
        state: stopped
        enabled: false
      
    - name: 2) 패키지 삭제
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      loop: "{{ mariadb_packages }}"
      when: ansible_distribution == "CentOS"
